var artifacttypes= [
	{ name: 'Section 6', code: 'section-6', multiple: true, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'pre-ea' },
	{ name: 'Threshold Determination', code: 'threshold-determination', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'pre-ea' },
	{ name: 'Project Description', code: 'project-description', milestone: 'project-description', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'pre-ea' },
	{ name: 'Section 7', code: 'section-7', milestone: 'section-7-3-order', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'pre-ea' },
	{ name: 'Substitution (Decision) Request', code: 'substitution--decision-request', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'pre-ea' },
	{ name: 'Section 10(1)(a)', code: 'section-10-1-a', milestone: 'section-10-1-a-order', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'pre-ea' },
	{ name: 'Section 10(1)(b)', code: 'section-10-1-b', milestone: 'section-10-1-b-order', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'pre-ea' },
	{ name: 'Section 10(1)(c)', code: 'section-10-1-c', milestone: 'section-10-1-c-order', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'pre-ea' },
	{ name: 'Section 10(1)(b) Fee Order', code: 'section-10-1-b-fee-order', milestone: 'section-10-1-b-fee', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'pre-ea' },
	{ name: 'Pre-Assessment Inspection Fees', code: 'pre-assessment-inspection-fees', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'pre-ea' },
	{ name: 'Aboriginal Consultation', code: 'aboriginal-consultation', multiple: true, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'pre-ea' },
	{ name: 'Pre-Assessment Working Group', code: 'pre-assessment-working-group', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'pre-ea' },
	{ name: 'Draft Application Information Requirements', code: 'draft-application-information-requirements', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'pre-app' },
	{ name: 'Application Information Requirements', code: 'application-information-requirements', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'pre-app' },
	{ name: 'Valued Component Selection Document', code: 'valued-component-selection-document', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'pre-app' },
	{ name: 'Section 11 Order', code: 'section-11-order', milestone: 'section-11-order', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'pre-app' },
	{ name: 'Section 13 Order', code: 'section-13-order', milestone: 'section-13-order', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'pre-app' },
	{ name: 'Section 14 Order', code: 'section-14-order', milestone: 'section-14-order', multiple: true, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'pre-app' },
	{ name: 'Section 15 Order', code: 'section-15-order', milestone: 'section-15-order', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'pre-app' },
	{ name: 'Assesment Fee #1 Fee Order', code: 'assesment-fee-1-fee-order', multiple: true, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'pre-app' },
	{ name: 'Pre-Application Inspection Fees', code: 'pre-application-inspection-fees', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'pre-app' },
	{ name: 'Pre-Application Working Group', code: 'pre-application-working-group', multiple: true, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'pre-app' },
	{ name: 'Evaluation Report', code: 'evaluation-report', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'evaluation' },
	{ name: 'Assesment Fee #2 Fee Order', code: 'assesment-fee-2-fee-order', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'evaluation' },
	{ name: 'Application Evaluation Working Group', code: 'application-evaluation-working-group', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'evaluation' },
	{ name: 'Application Package', code: 'application-package', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'application-review' },
	{ name: 'Public Consultation Report', code: 'public-consultation-report', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'application-review' },
	{ name: 'Aboriginal Consultation Report', code: 'aboriginal-consultation-report', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'application-review' },
	{ name: 'WG Consultation Report', code: 'wg-consultation-report', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'application-review' },
	{ name: 'Referral Package', code: 'referral-package', milestone: 'referral-package', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'application-review' },
	{ name: 'Application Review Working Group', code: 'application-review-working-group', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'application-review' },
	{ name: 'Decision Package', code: 'decision-package', milestone: 'decision-package', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'decision' },
	{ name: 'Certificate', code: 'certificate', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'decision' },
	{ name: 'Project Management Plans', code: 'project-management-plans', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'post-certification' },
	{ name: 'Project Monitoring Plans', code: 'project-monitoring-plans', multiple: true, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'post-certification' },
	{ name: 'Project Studies', code: 'project-studies', multiple: true, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'post-certification' },
	{ name: 'Certificate Extension', code: 'certificate-extension', milestone: 'ea-certificate-extension', multiple: true, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'post-certification' },
	{ name: 'Certificate Extension Fee Order', code: 'certificate-extension-fee-order', milestone: 'ea-certificate-extension-fee', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'post-certification' },
	{ name: 'Substatially Started Decision', code: 'substatially-started-decision', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'post-certification' },
	{ name: 'Certificate Amendment', code: 'certificate-amendment', milestone: 'ea-certificate-amendment', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'post-certification' },
	{ name: 'Certificate Amendment Fee Order', code: 'certificate-amendment-fee-order', milestone: 'ea-certificate-amendment-fee', multiple: true, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'post-certification' },
	{ name: 'Amendment Working Group', code: 'amendment-working-group', multiple: true, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'post-certification' },
	{ name: 'Amendment Aboriginal Consultation', code: 'amendment-aboriginal-consultation', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'post-certification' },
	{ name: 'Post Certififaction Inspection Fees', code: 'post-certififaction-inspection-fees', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: 'post-certification' },
	{ name: 'Project Termination', code: 'project-termination', milestone: 'project-termination', multiple: true, isTemplate: false, versions: [ 'Draft', 'Final'], phase: '' },
	{ name: 'Project Withdrawal', code: 'project-withdrawal', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: '' },
	{ name: 'Certificate Suspension', code: 'certificate-suspension', milestone: 'ea-certificate-suspension-s-37-1', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: '' },
	{ name: 'Certificate Cancellation ', code: 'certificate-cancellation', milestone: 'ea-certificate-cancellation-s-37-1', multiple: true, isTemplate: false, versions: [ 'Draft', 'Final'], phase: '' },
	{ name: 'Timeline Suspension', code: 'timeline-suspension', milestone: 'time-limit-suspension-s-24-2', multiple: false, isTemplate: false, versions: [ 'Draft', 'Final'], phase: '' },
	{ name: 'Timeline Extension', code: 'timeline-extension', milestone: 'time-limit-extension-s-30-2', multiple: true, isTemplate: false, versions: [ 'Draft', 'Final'], phase: '' },
];
module.exports = { artifacttypes: artifacttypes};
