module.exports = [

{

	'permit':'M-238',
	'name':'Bonanza Ledge',
	'prop':'Barkerville Gold Mines Ltd.',
	'ownership':'Barkerville Gold Mines Ltd.',
	'lat':53.089722,
	'lon':-121.561389,
	'status':'Operating',
	'comm':'gold',
	'memRegion':'South Central (Kamloops office)',
	'tail':0,

	'description':null

},
{
'permit':'C-84',
'name':'Coal Mountain',
'prop':'Teck Coal Limited',
'ownership':'Teck Resources Limited',
'lat':49.513,
'lon':-114.655,
'status':'Operating',
'comm':'coal',
'memRegion':'Southeast (Cranbrook)',
'tail':0,
'description':null
},
{
'permit':'M-29',
'name':'Copper Mountain (Similco)',
'prop':'Copper Mountain Mining Corporation',
'ownership':'Copper Mountain Mining Corporation',
'lat':49.33111,
'lon':-120.53417,
'status':'Operating',
'comm':'copper, gold, silver',
'memRegion':'South Central (Kamloops office)',
'tail':1,
'description':null
},
{
'permit':'C-2',
'name':'Elkview',
'prop':'Teck Coal Limited',
'ownership':'Teck Resources Limited',
'lat':49.74500,
'lon':-114.83000,
'status':'Operating',
'comm':'coal',
'memRegion':'Southeast (Cranbrook)',
'tail':5,
'description':null
},
{
'permit':'C-3',
'name':'Fording River',
'prop':'Teck Coal Limited',
'ownership':'Teck Resources Limited',
'lat':50.16200,
'lon':-114.91100,
'status':'Operating',
'comm':'coal',
'memRegion':'Southeast (Cranbrook)',
'tail':2,
'description':null
},
{
'permit':'M-40',
'name':'Gibraltar',
'prop':'Gibraltar Mines Ltd.',
'ownership':'Taseko Mines Limited – 75%\nCariboo Mining Corporation (Sojitz Corp., Dowa Holdings Co. Ltd.  & Furukawa Co. Ltd.) – 25%',
'lat':52.52750,
'lon':-122.32138,
'status':'Operating',
'comm':'copper, molybdenum',
'memRegion':'South Central (Kamloops office)',
'tail':1,
'description':null
},
{
'permit':'C-137',
'name':'Greenhills',
'prop':'Teck Coal Limited (operator)',
'ownership':'Teck Resources Limited – 80%\nPOSCO (South Korea) – 20%',
'lat':50.20028,
'lon':-115.00830,
'status':'Operating',
'comm':'coal',
'memRegion':'Southeast (Cranbrook)',
'tail':1,
'description':null
},
{
'permit':'M-11',
'name':'Highland Valley Copper',
'prop':'Teck Highland Valley Copper Partnership',
'ownership':'Teck Resources Limited',
'lat':50.43670,
'lon':-120.90450,
'status':'Operating',
'comm':'copper, molybdenum',
'memRegion':'South Central (Kamloops office)',
'tail':5,
'description':null
},
{
'permit':'M-203',
'name':'Huckleberry',
'prop':'Huckleberry Mines Ltd.',
'ownership':'Imperial Metals Corporation',
'lat':53.68278,
'lon':-127.17389,
'status':'Operating',
'comm':'copper, molybdenum',
'memRegion':'Northwest (Smithers office)',
'tail':2,
'description':null
},
{
'permit':'C-129',
'name':'Line Creek',
'prop':'Teck Coal Limited',
'ownership':'Teck Resources Limited – 100%',
'lat':49.917,
'lon':-114.776,
'status':'Operating',
'comm':'coal',
'memRegion':'Southeast (Cranbrook)',
'tail':0,
'description':null
},
{
'permit':'M-236',
'name':'Mount Milligan',
'prop':'Thompson Creek Metals Company Inc.',
'ownership':'Thompson Creek Metals Company Inc.',
'lat':55.17000,
'lon':-123.88400,
'status':'Operating',
'comm':'copper, gold',
'memRegion':'Central-Northeast (Prince George office)',
'tail':1,
'description':null
},
{
'permit':'M-200',
'name':'Mount Polley',
'prop':'Mount Polley Mining Corporation',
'ownership':'Imperial Metals Corporation',
'lat':52.54881,
'lon':-121.64068,
'status':'Operating',
'comm':'gold, copper',
'memRegion':'South Central (Kamloops office)',
'tail':1,
'description':null
},
{
'permit':'M-229',
'name':'New Afton',
'prop':'New Gold Inc.',
'ownership':'New Gold Inc. – 100%',
'lat':50.65146,
'lon':-120.50876,
'status':'Operating',
'comm':'copper, gold',
'memRegion':'South Central (Kamloops office)',
'tail':2,
'description':null
},
{
'permit':'G-225',
'name':'Orca Sand and Gravel Quarry',
'prop':'Orca Sand & Gravel Ltd.',
'ownership':'Polaris Minerals Corporation – 88%\nNamgis First Nation – 12%',
'lat':50.5828,
'lon':-127.1394,
'status':'Operating',
'comm':'sand & gravel',
'memRegion':'Southwest (Victoria office)',
'tail':0,
'description':null
},
{
'permit':'M-240',
'name':'Red Chris',
'prop':'Red Chris Development Company Ltd.',
'ownership':'Imperial Metals Corporation',
'lat':57.7049,
'lon':-129.79142,
'status':'Operating',
'comm':'copper, gold',
'memRegion':'Northwest (Smithers office)',
'tail':1,
'description':null
},
{
'permit':'M-243',
'name':'Brucejack',
'prop':'Pretium Resources Inc. (Pretivm)',
'ownership':'Pretium Resources Inc. (Pretivm)',
'lat':56.4675,
'lon':-130.19333,
'status':'Under Construction',
'comm':'gold, silver',
'memRegion':'Northwest (Smithers office)',
'tail':0,
'description':null
},
{
'permit':'M-10',
'name':'Kitsault',
'prop':'Avanti Kitsault Mine Ltd.',
'ownership':'Alloycorp Mining Inc.',
'lat':55.421944,
'lon':-129.419444,
'status':'Under Construction',
'comm':'molybdenum',
'memRegion':'Northwest (Smithers office)',
'tail':0,
'description':null
},
{
'permit':'M-242',
'name':'Silvertip',
'prop':'JDS Silver Inc.',
'ownership':'JDS Silver Inc. – 100%',
'lat':59.92667,
'lon':-130.342,
'status':'Under Construction',
'comm':'silver, lead, zinc',
'memRegion':'Northwest (Smithers office)',
'tail':0,
'description':'The Silvertip project is located in northern BC, approximately 16 kilometers south of the Yukon border and 90 km southwest of Watson Lake. The site is within the Silvertip Creek valley, in the Tootsee River watershed.'
},
{
'permit':'N/A',
'name':'KSM (Kerr-Sulphurets-Mitchell)',
'prop':'Seabridge Gold Ltd.',
'ownership':'Seabridge Gold Ltd. – 100%',
'lat':56.51944,
'lon':-130.25472,
'status':'Under Construction (phase 1)',
'comm':'gold, copper',
'memRegion':'Northwest (Smithers office)',
'tail':null,
'description':null
},
{
'permit':'N/A',
'name':'Murray River',
'prop':'HD Mining International Ltd.',
'ownership':'Huiyong Holdings Ltd. – 55%\nCanadian Dehua International Mines Group Ltd. – 40%\nUnnamed partner – 5%',
'lat':55.013,
'lon':-121.036,
'status':'Pre-application (permitting)',
'comm':'coal',
'memRegion':'Central-Northeast (Prince George office)',
'tail':null,
'description':null
},
{
'permit':'M-181',
'name':'Moberly Silica',
'prop':'HCA Mountain Minerals (Moberly) Ltd.',
'ownership':'Heemskirk Canada (Heemskirk Consolidated Limited)',
'lat':51.36668,
'lon':-116.96510,
'status':'Operating',
'comm':'silica',
'memRegion':'Southeast (Cranbrook)',
'tail':1,
'description':null
},
{
'permit':'M-198',
'name':'QR – Barkerville Gold Mines',
'prop':'Barkerville Gold Mines Ltd.',
'ownership':'Barkerville Gold Mines Ltd.',
'lat':52.66667,
'lon':-121.78333,
'status':'Mill is operating, but no mining operations are taking place onsite',
'comm':'gold',
'memRegion':'South Central (Kamloops office)',
'tail':1,
'description':null
},
{
'permit':'M-112',
'name':'Afton/Ajax/Abacus',
'prop':'Afton Operating Corporation',
'ownership':'KGHM International Ltd.',
'lat':50.64917,
'lon':-120.50000,
'status':'Closed',
'comm':'copper, gold',
'memRegion':'South Central (Kamloops office)',
'tail':2,
'description':null
},
{
'permit':'M-50',
'name':'Alwin',
'prop':'N/A',
'ownership':'Under MEM care',
'lat':50.47742,
'lon':-121.10114,
'status':'Closed (Historical)',
'comm':'copper',
'memRegion':'South Central (Kamloops office)',
'tail':1,
'description':null
},
{
'permit':'C-217',
'name':'Basin Coal/Tulameen',
'prop':'',
'ownership':'Coalmont Energy Corporation',
'lat':49.50889,
'lon':-120.76694,
'status':'Care & Maintenance',
'comm':'coal',
'memRegion':'South Central (Kamloops office)',
'tail':5,
'description':null
},
{
'permit':'M-71',
'name':'Beaverdell',
'prop':'',
'ownership':'Teck Resources Limited',
'lat':49.43222,
'lon':-119.06111,
'status':'Closed',
'comm':'silver, lead, zinc',
'memRegion':'Southeast (Cranbrook office)',
'tail':2,
'description':null
},
{
'permit':'M-35',
'name':'Bell',
'prop':'Xstrata Canada Corporation',
'ownership':'Glencore Canada Corporation',
'lat':55.00300,
'lon':-126.23100,
'status':'Closed',
'comm':'copper, gold, silver',
'memRegion':'Northwest (Smithers office)',
'tail':1,
'description':null
},
{
'permit':'M-171',
'name':'Blackdome',
'prop':'Sona Resources Corp.',
'ownership':'Sona Resources Corp.',
'lat':51.31583,
'lon':-122.49916,
'status':'Closed',
'comm':'gold',
'memRegion':'South Central (Kamloops office)',
'tail':1,
'description':null
},
{
'permit':'M-101',
'name':'Boss Mountain',
'prop':'Glencore Canada Corporation',
'ownership':'Glencore Canada Corporation',
'lat':52.09667,
'lon':-120.90750,
'status':'Closed',
'comm':'molybdenum',
'memRegion':'South Central (Kamloops office)',
'tail':1,
'description':null
},
{
'permit':'M-207',
'name':'Bralorne',
'prop':'Bralorne Gold Mines Ltd.',
'ownership':'Avino Silver & Gold Mines Ltd.',
'lat':50.78020,
'lon':-122.80850,
'status':'Care & Maintenance',
'comm':'gold',
'memRegion':'South Central (Kamloops office)',
'tail':1,
'description':null
},
{
'permit':'M-12',
'name':'Brenda',
'prop':'Glencore Canada Corporation',
'ownership':'Glencore Canada Corporation',
'lat':49.87944,
'lon':-120.00639,
'status':'Closed',
'comm':'copper, molybdenum',
'memRegion':'South Central (Kamloops office)',
'tail':1,
'description':null
},
{
'permit':'C-221',
'name':'Brule (Dillon)',
'prop':'Brule Coal Partnership',
'ownership':'Walter Energy Inc.',
'lat':55.38667,
'lon':-121.82,
'status':'Care & Maintenance',
'comm':'coal',
'memRegion':'Central-Northeast (Prince George office)',
'tail':0,
'description':null
},
{
'permit':'C-158',
'name':'Bullmoose',
'prop':'Teck Coal Ltd.',
'ownership':'Teck Resources Limited',
'lat':55.15000,
'lon':-121.55000,
'status':'Closed',
'comm':'coal',
'memRegion':'Central-Northeast (Prince George office)',
'tail':1,
'description':null
},
{
'permit':'M-138',
'name':'Carolin/Ladner Creek',
'prop':'New Carolin Gold Corp.',
'ownership':'New Carolin Gold Corp.',
'lat':49.49583,
'lon':-121.28750,
'status':'Closed',
'comm':'gold',
'memRegion':'Southwest (Victoria office)',
'tail':1,
'description':null
},
{
'permit':'M-18',
'name':'Cassiar-McDame',
'prop':'Cassiar Jade Contracting Inc.',
'ownership':'Cassiar Jade Contracting Inc.',
'lat':59.33996,
'lon':-129.83967,
'status':'Closed',
'comm':'asbestos',
'memRegion':'Northwest (Smithers office)',
'tail':1,
'description':null
},
{
'permit':'M-68',
'name':'Craigmont',
'prop':'Huldra Properties Inc.',
'ownership':'Nicola Mining Inc.',
'lat':50.18452,
'lon':-120.87912,
'status':'Closed',
'comm':'magnetite',
'memRegion':'South Central (Kamloops office)',
'tail':2,
'description':null
},
{
'permit':'M-95',
'name':'Dankoe',
'prop':'439813 B.C. Ltd.',
'ownership':'439813 B.C. Ltd.',
'lat':49.05694,
'lon':-119.69000,
'status':'Closed',
'comm':'silver',
'memRegion':'South Central (Kamloops office)',
'tail':1,
'description':null
},
{
'permit':'M-4',
'name':'Endako',
'prop':'Thompson Creek Mining Ltd.',
'ownership':'Thompson Creek Metals Company Inc.',
'lat':54.03959,
'lon':-125.13473,
'status':'Care & Maintenance',
'comm':'molybdenum',
'memRegion':'Northwest (Smithers office)',
'tail':3,
'description':null
},
{
'permit':'M-114',
'name':'Equity Silver',
'prop':'Goldcorp Canada Ltd.',
'ownership':'Goldcorp Inc.',
'lat':54.18944,
'lon':-126.26333,
'status':'Closed',
'comm':'silver',
'memRegion':'Northwest (Smithers office)',
'tail':1,
'description':null
},
{
'permit':'M-197',
'name':'Eskay Creek',
'prop':'Barrick Gold Inc.',
'ownership':'Barrick Gold Corporation',
'lat':56.64650,
'lon':-130.44370,
'status':'Closed',
'comm':'gold',
'memRegion':'Northwest (Smithers office)',
'tail':1,
'description':null
},
{
'permit':'M-33',
'name':'Gallowai/Bul River',
'prop':'Bul River Mineral Corporation',
'ownership':'Purcell Basin Minerals Inc.',
'lat':49.50470,
'lon':-115.36667,
'status':'Care & Maintenance',
'comm':'copper',
'memRegion':'Southeast (Cranbrook office)',
'tail':1,
'description':null
},
{
'permit':'M-64',
'name':'Giant Nickel/Pride of Emory',
'prop':'Barrick Gold Inc.',
'ownership':'Barrick Gold Corporation',
'lat':49.48500,
'lon':-121.46056,
'status':'Closed',
'comm':'nickel',
'memRegion':'Southwest (Victoria office)',
'tail':2,
'description':null
},
{
'permit':'M-187',
'name':'Golden Bear',
'prop':'North American Metals Company',
'ownership':'Goldcorp Inc.',
'lat':58.51667,
'lon':-132.28333,
'status':'Closed',
'comm':'gold',
'memRegion':'Northwest (Smithers office)',
'tail':1,
'description':null
},
{
'permit':'M-147',
'name':'Goldstream',
'prop':'Barkerville Gold Mines Ltd.',
'ownership':'Barkerville Gold Mines Ltd.',
'lat':51.63034,
'lon':-118.42823,
'status':'Closed',
'comm':'gold, silver',
'memRegion':'Southeast (Cranbrook office)',
'tail':1,
'description':null
},
{
'permit':'M-6',
'name':'Granisle',
'prop':'Glencore Canada Corporation',
'ownership':'Glencore Canada Corporation',
'lat':54.56400,
'lon':-126.09300,
'status':'Closed',
'comm':'copper',
'memRegion':'Northwest (Smithers office)',
'tail':2,
'description':null
},
{
'permit':'M-233',
'name':'Greenwood (Zip)',
'prop':'Huakan International Mining Inc.',
'ownership':'Huakan International Mining Inc.',
'lat':49.08639,
'lon':-118.56806,
'status':'Care & Maintenance',
'comm':'silver',
'memRegion':'Southeast (Cranbrook office)',
'tail':1,
'description':null
},
{
'permit':'M-218',
'name':'HB Tailings Landfill',
'prop':'Regional District of Central Kootenay',
'ownership':'Regional District of Central Kootenay',
'lat':49.13790,
'lon':-117.24216,
'status':'Closed',
'comm':'lead, zinc',
'memRegion':'Southeast (Cranbrook office)',
'tail':1,
'description':null
},
{
'permit':'M-178',
'name':'Johnny Mountain',
'prop':'Skyline Gold Corporation',
'ownership':'Snip Gold Corp.',
'lat':56.63333,
'lon':-131.08333,
'status':'Closed',
'comm':'gold',
'memRegion':'Northwest (Smithers office)',
'tail':1,
'description':null
},
{
'permit':'M-8',
'name':'Jumbo/Red Mountain',
'prop':'Under Ministry of Energy and Mines care',
'ownership':'Under Ministry of Energy and Mines care',
'lat':50.40000,
'lon':-116.46667,
'status':'Closed',
'comm':'gold, silver',
'memRegion':'Southeast (Cranbrook office)',
'tail':1,
'description':null
},
{
'permit':'M-206',
'name':'Kemess South',
'prop':'AuRico Gold Inc.',
'ownership':'Alamos Gold Inc.',
'lat':57.06200,
'lon':-126.70000,
'status':'Closed',
'comm':'copper, gold',
'memRegion':'Central-Northeast (Prince George office)',
'tail':1,
'description':null
},
{
'permit':'M-174',
'name':'Lawyers/Cheni',
'prop':'Under Ministry of Energy and Mines care',
'ownership':'Under Ministry of Energy and Mines care',
'lat':57.33333,
'lon':-127.16667,
'status':'Closed',
'comm':'gold, silver',
'memRegion':'Northwest (Smithers office)',
'tail':1,
'description':null
},
{
'permit':'M-215',
'name':'Lumby Project/Quinto',
'prop':'Quinto Technology Inc.',
'ownership':'Quinto Technology Inc.',
'lat':50.26558,
'lon':-118.94027,
'status':'Closed',
'comm':'mica',
'memRegion':'South Central (Kamloops office)',
'tail':2,
'description':null
},
{
'permit':'M-226',
'name':'Max Molybdenum',
'prop':'FortyTwo Metals Inc.',
'ownership':'Discovery Ventures Inc.',
'lat':50.63758,
'lon':-117.58544,
'status':'Care & Maintenance',
'comm':'molybdenum',
'memRegion':'Southeast (Cranbrook office)',
'tail':1,
'description':null
},
{
'permit':'M-209',
'name':'May Mac',
'prop':'Golden Dawn Minerals Inc.',
'ownership':'Golden Dawn Minerals Inc.',
'lat':49.01190,
'lon':-118.70400,
'status':'Care & Maintenance',
'comm':'silver, lead',
'memRegion':'Southeast (Cranbrook office)',
'tail':1,
'description':null
},
{
'permit':'M-133',
'name':'Mosquito Creek',
'prop':'Mosquito Consolidated Gold Mines Ltd.',
'ownership':'Barkerville Gold Mines Ltd.',
'lat':53.11056,
'lon':-121.59361,
'status':'Care & Maintenance',
'comm':'gold',
'memRegion':'South Central (Kamloops office)',
'tail':1,
'description':null
},
{
'permit':'M-26',
'name':'Myra Falls',
'prop':'Nyrstar Myra Falls Ltd.',
'ownership':'Nyrstar N.V.',
'lat':49.55388,
'lon':-125.56055,
'status':'Care & Maintenance',
'comm':'copper, lead, zinc',
'memRegion':'Southwest (Victoria office)',
'tail':2,
'description':null
},
{
'permit':'M-173',
'name':'Nickel Plate',
'prop':'Barrick Gold Inc.',
'ownership':'Barrick Gold Corporation',
'lat':49.3667,
'lon':-120.03333,
'status':'Closed',
'comm':'gold',
'memRegion':'South Central (Kamloops office)',
'tail':1,
'description':null
},
{
'permit':'M-5',
'name':'Pinchi Lake',
'prop':'Teck Metals Ltd.',
'ownership':'Teck Resources Limited',
'lat':56.00449,
'lon':-125.55880,
'status':'Closed',
'comm':'magnetite',
'memRegion':'Central-Northeast (Prince George office)',
'tail':2,
'description':null
},
{
'permit':'M-179',
'name':'Premier Gold Project',
'prop':'Boliden Ltd.',
'ownership':'Ascot Resources Ltd.',
'lat':56.11667,
'lon':-130.01667,
'status':'Closed',
'comm':'gold',
'memRegion':'Northwest (Smithers office)',
'tail':1,
'description':null
},
{
'permit':'C-172',
'name':'Quinsam',
'prop':'Quinsam Coal Corporation',
'ownership':'Hillsborough Resources Canada (a fully owned subsidiary of Vitol Anker International B.V., a member of the Vitol Group) – 100%',
'lat':49.94950,
'lon':-125.35320,
'status':'Care & Maintenance',
'comm':'thermal coal',
'memRegion':'Southwest (Victoria office)',
'tail':2,
'description':null
},
{
'permit':'C-156',
'name':'Quintette',
'prop':'Teck Coal Ltd.',
'ownership':'Teck Resources Limited',
'lat':54.94200,
'lon':-120.96200,
'status':'Care & Maintenance',
'comm':'coal',
'memRegion':'Central-Northeast (Prince George office)',
'tail':2,
'description':null
},
{
'permit':'M-184',
'name':'Samatosum',
'prop':'FQM (Akubra) Inc.',
'ownership':'First Quantum Minerals Ltd.',
'lat':51.81858,
'lon':-119.81858,
'status':'Closed',
'comm':'silver',
'memRegion':'South Central (Kamloops office)',
'tail':1,
'description':null
},
{
'permit':'M-189',
'name':'Shasta/Multinational B & Baker Mill',
'prop':'Sable Resources Ltd.',
'ownership':'Sable Resources Ltd.',
'lat':57.27400,
'lon':-127.03100,
'status':'Care & Maintenance',
'comm':'gold',
'memRegion':'Central-Northeast (Prince George office)',
'tail':2,
'description':null
},
{
'permit':'M-65',
'name':'Silvana/Klondike Silver/Hinckley',
'prop':'Klondike Gold Corp. and Slocan Minerals Ltd.',
'ownership':'Klondike Gold Corp. and Slocan Minerals Ltd.',
'lat':49.96667,
'lon':-117.25000,
'status':'Care & Maintenance',
'comm':'silver',
'memRegion':'Southeast (Cranbrook office)',
'tail':3,
'description':null
},
{
'permit':'M-190',
'name':'Snip',
'prop':'Barrick Gold Inc.',
'ownership':'Barrick Gold Corporation',
'lat':56.6667,
'lon':-131.08333,
'status':'Closed',
'comm':'gold',
'memRegion':'Northwest (Smithers office)',
'tail':1,
'description':null
},
{
'permit':'M-74',
'name':'Sullivan',
'prop':'Teck Metals Ltd.',
'ownership':'Teck Resources Limited',
'lat':49.70750,
'lon':-116.00528,
'status':'Closed',
'comm':'silver, lead, zinc',
'memRegion':'Southeast (Cranbrook office)',
'tail':7,
'description':null
},
{
'permit':'m-127',
'name':'Table Mountain/Cusac',
'prop':'China Materials/Cassiar Gold Inc. ',
'ownership':'China Materials/Cassiar Gold Inc.',
'lat':59.18370,
'lon':-129.69240,
'status':'Care & Maintenance',
'comm':'gold',
'memRegion':'Northwest (Smithers office)',
'tail':2,
'description':null
},
{
'permit':'M-149',
'name':'Taurus Gold',
'prop':'Cassiar Gold Corporation',
'ownership':'China Materials/Cassiar Gold Inc.',
'lat':59.27444,
'lon':-129.68944,
'status':'Closed',
'comm':'gold',
'memRegion':'Northwest (Smithers office)',
'tail':1,
'description':null
},
{
'permit':'C-224',
'name':'Trend-Roman',
'prop':'Peace River Coal Inc.',
'ownership':'Anglo American',
'lat':54.8995,
'lon':-120.9774,
'status':'Care & Maintenance',
'comm':'coal',
'memRegion':'Central-Northeast (Prince George office)',
'tail':0,
'description':null
},
{
'permit':'C-153',
'name':'Willow Creek',
'prop':'Willow Creek Coal Partnership',
'ownership':'Walter Energy Inc.',
'lat':null,
'lon':null,
'status':'Care & Maintenance',
'comm':'coal',
'memRegion':'Central-Northeast (Prince George office)',
'tail':0,
'description':null
},
{
'permit':'C-223',
'name':'Wolverine',
'prop':'Wolverine Coal Partnership',
'ownership':'Walter Energy Inc.',
'lat':55.08751,
'lon':-121.24977,
'status':'Care & Maintenance',
'comm':'coal',
'memRegion':'Central-Northeast (Prince George office)',
'tail':1,
'description':null
},
{
'permit':'M-241',
'name':'Yellow Giant',
'prop':'Banks Island Gold Ltd.',
'ownership':'Banks Island Gold Ltd.',
'lat':53.369167,
'lon':-130.128056,
'status':'Closed',
'comm':'gold',
'memRegion':'Northwest (Smithers office)',
'tail':0,
'description':null
},
{
'permit':'M-235',
'name':'Yellowjacket',
'prop':'African Queen Mines Ltd.',
'ownership':'African Queen Mines Ltd.',
'lat':59.59461,
'lon':-133.54892,
'status':'Care & Maintenance',
'comm':'gold',
'memRegion':'Northwest (Smithers office)',
'tail':1,
'description':null
}

];
